name: CD-Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: [completed]
    branches: [main]

  env:
    IMAGE_NAME: bookstore-api
    IMAGE_TAG: ${{ github.event.workflow_run.head_sha }}


  jobs:
    deploy:
      runs-on: ubuntu-latest
      if: $ {{ github.event.workflow_run.conclusion == 'success' }}

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
